apiVersion: v1
kind: Service
metadata:
  name: docker-react-app
  namespace: demo
spec:
  ports:
  - port: 80
    targetPort: react-port
    protocol: TCP
  selector:
    app: docker-react-app
  type: NodePort
