---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-react-app
  labels:
    app: docker-react-app
  annotations:
    fluxcd.io/automated: "true"
    fluxcd.io/tag.abhishekksingh/docker-react-app: semver:~1.0.0
spec:
  strategy:
    rollingUpdate:
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      app: docker-react-app
  template:
    metadata:
      labels:
        app: docker-react-app
    spec:
      containers:
      - name: docker-react-app
        image: abhishekksingh/docker-react-app:1.0.1
        ports:
        - name: react-port
          containerPort: 5000
